---
title: "Chromosome Walking: Partitioning Neutral & Putatively Adaptive Variation Using Conditional Covariance"
description: |
  Across the genome, genetic covariance among spatially sampled populations is largely constrained by historical demographic processes.  At specific regions within the genome, selection can change this covariance structure. The extent and magnitude of this deviation is dependent upon differential pressures selective processes have exerted on alternative populations.   In this manuscript, we examine the use of conditional genetic covariance as determined by topological structure of Population Graphs to examine the change in genetic covariance along contiguous stretches of chromosomes.  We start by analyzing simulated scenarios depicting specific patterns of selection to determine what graph-theoretic features of a population graph topology are modified by selection.  Using these parameters we then apply this technique to a dense set of SNP markers from the second chromosome in the human genome, a commonly used example dataset from CEPH for demonstrating the operation of selection.  We show that, in addition to identifying regions thought to be under selective pressure using existing methodologies, we are also able to classify the outlier genomic regions into groups based upon the topological similarity of population graph structure.  This approach is unique in that it provides a way to: 1) identify outliers based on topological patterns in the among population covariance structure, 2) classify genomic regions whose distribution of among population genetic covariance deviates into definable groups, and 3) allows searching of genomic regions whose covariance is based upon external hypothesis.  We close by discussing the extensions of the chromosome walking approach to examining other selective regimes such as negative selection, similarity in selective response due to epistatic interactions, and correlation of selective patterns within biological pathways.

author:
  - name: Rodney J. Dyer
    url: https://dyerlab.org
    affiliation: Center for Environmental Studies<br>Virginia Commonwealth University<br>&nbsp;
    affiliation_url: https://ces.vcu.edu
    orcid_id: 0000-0003-4707-3453
  - name: Brian C. Verrelli
    url: https://rampages.us/bcverrelli/
    affiliation: Center for Biological Data Science<br>Virginia Commonwealth University<br>&nbsp;
    affiliation_url: https://cbds.vcu.edu
    orcid_id: 0000-0002-9670-4920
  - name: Andrew J. Eckert
    url: https://www.eckertlab.com/
    affiliation: Department of Biology<br>Virginia Commonwealth University
    affiliation_url: https://biology.vcu.edu
    orcid_id: 0000-0002-6522-2646
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Introduction

```{r child = 'introduction.Rmd'}
```

## Materials & Methods

```{r child = 'methods.Rmd'}
```



